
server:
  port: 8111
  tomcat:
    uri-encoding: UTF-8
web:
  domain:
    site: http://localhost:${server.port}
    upload: ${web.domain.site}/upload/
  updateDir: "d:/upload/"


#mybatisGenerate 读文件的时候怕属性冲突，所以自定义属性
pro_db_url: jdbc:mysql://localhost:3306/test
pro_db_driver_class: com.mysql.jdbc.Driver
pro_db_username: root
pro_db_password: 123123

spring:
  application:
    name: service-auth
  datasource:
    druid:
      url: ${pro_db_url}
      username: ${pro_db_username}
      password: ${pro_db_password}
      driver-class-name: ${pro_db_driver_class}
      pool-prepared-statements: true
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      min-idle: 20
      max-idle: 1000
      max-active: 1000
      max-wait: 30000
  data:
    elasticsearch:
      #cluster-name: #默认为elasticsearch
      #cluster-nodes: 127.0.0.1: #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      properties:
        path:
          logs: ${web.updateDir}/elasticsearch/log #elasticsearch日志存储目录
          data: ${web.updateDir}/elasticsearch/data #elasticsearch数据存储目录


mybatis:
  type-aliases-package: pers.cjr.chatbot.nb.table.model
  mapper-locations:
                  - classpath:mapper/*Mapper.xml
                  - classpath:mapper/**/*Mapper.xml

mapper:
  mappers:
    - pers.cjr.chatbot.nb.core.mybatis.mapper.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

logging:
  file: ${web.updateDir}/log/chatbot_nb.log
  level:
    info: INFO
    debug: DEBUG
    error: ERROR